### PR TITLE
Fixes for report being created at a new location using the latest surefire plugin 

### LINKED ISSUE #340: Test reports can be in a new location
Refer to https://github.com/OpenLiberty/liberty-tools-intellij/issues/934 from LTI.

With the recent updates to version `3.5.0` for the Maven Surefire Plugin and Maven Failsafe Plugin, test reports are created in a new location by default.

We need to update the code where we currently hardcode the old location: https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/src/liberty/devCommands.ts#L493

The current proposal is to check both new and old report locations, starting with the new location first.

### PR DESCRIPTION
**Pull request by JoshwinThomasIBM**
Fixes #340  , Fixes for report being created at a new location using the latest surefire plugin, now this checks the previous location as well as the new location for reports, also included test test cases for considering the new locations

### CODE REVIEW

File: src/liberty/devCommands.ts [hunk 1]
```diff
@@ -490,28 +490,29 @@ export async function openReport(reportType: string, libProject?: LibertyProject
         if (path !== undefined) {
             let report: any;
             if (libProject.getContextValue() === LIBERTY_MAVEN_PROJECT || libProject.getContextValue() === LIBERTY_MAVEN_PROJECT_CONTAINER) {
-                report = Path.join(path, "target", "site", reportType + "-report.html");
+                //report = Path.join(path, "target", "site", reportType + "-report.html");
```
Comment (aparnamichael) [inline src/liberty/devCommands.ts:493]: Remove the commented line of code.

**Comment by aparnamichael** [comment]
@JoshwinThomasIBM Update the year in the copyright header.

File: src/liberty/devCommands.ts [hunk 2]
```diff
@@ -610,4 +611,32 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
  */
 function isWin(): boolean {
     return process.platform.startsWith("win");
-}
\ No newline at end of file
+}
+
+function getReportFile(path :any,dir :string,filename:string):any{
+    console.log("inside getReportFile path::"+path+"::dir::"+dir+"::fileName::"+filename);
+    console.log("::path::"+Path.join(path,"target",dir,filename));
```
Comment (aparnamichael) [inline src/liberty/devCommands.ts:618]: Remove the unnecessary log statements.

File: src/liberty/devCommands.ts [hunk 3]
```diff
@@ -610,4 +611,32 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
+    return Path.join(path,"target",dir, filename);
+}
+
+/*
+Function will check if the report is available within the given path and returns a boolean based on it and also 
+  the report will be displayed if it is available
+*/
+function checkReportExists(report : any,reportType : string,reportTypeLabel: string,libProject :LibertyProject): Promise<boolean> {
```
Comment (aparnamichael) [inline src/liberty/devCommands.ts:626]: Please rename this method, as it not only checks for the report's existence but also opens it in a web view.

Comment (aparnamichael) [reply src/liberty/devCommands.ts:626]: or add a new method for displaying report and use this method only to check report exist or not.

File: src/test/MavenTestDevModeActions.ts [hunk 4]
```diff
@@ -111,7 +113,8 @@ it('start maven with options from liberty dashboard', async () => {
   {
     console.log("Server succuessfully started");  
     let checkFile = await utils.checkIfTestReportExists(reportPath);
-    expect (checkFile).to.be.true;
+    let checkFile35 = await utils.checkIfTestReportExists(reportPath35);
```
Comment (aparnamichael) [inline src/test/MavenTestDevModeActions.ts:116]: use meaningful name for the variables.

File: src/test/MavenTestDevModeActions.ts [hunk 5]
```diff
@@ -129,8 +132,10 @@ it('start maven with options from liberty dashboard', async () => {
 it('start maven with history from liberty dashboard', async () => {  
 
   const reportPath = path.join(utils.getMvnProjectPath(),"target","site","failsafe-report.html");
-  const deleteReport = await utils.deleteReports(reportPath);
-  expect (deleteReport).to.be.true;  
+  const reportPath35 = path.join(utils.getMvnProjectPath(),"target","reports","failsafe.html");
```
Comment (aparnamichael) [inline src/test/MavenTestDevModeActions.ts:135]: use meaningful name for the variables.

File: src/test/MavenTestDevModeActions.ts [hunk 6]
```diff
@@ -129,8 +132,10 @@ it('start maven with options from liberty dashboard', async () => {
...
+  let deleteReport = await utils.deleteReports(reportPath);
+  let deleteReport35 = await utils.deleteReports(reportPath35);
```
Comment (aparnamichael) [inline src/test/MavenTestDevModeActions.ts:137]: same here

File: src/test/MavenTestDevModeActions.ts [hunk 7]
```diff
@@ -142,7 +147,8 @@ it('start maven with history from liberty dashboard', async () => {
   {
     console.log("Server succuessfully started");  
     let checkFile = await utils.checkIfTestReportExists(reportPath);
-    expect (checkFile).to.be.true;
+    let checkFile35 = await utils.checkIfTestReportExists(reportPath35);
```
Comment (aparnamichael) [inline src/test/MavenTestDevModeActions.ts:150]: same here

File: src/liberty/devCommands.ts [hunk 8]
```diff
@@ -490,28 +490,28 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
-                        reportType, // Identifies the type of the webview. Used internally
-                        libProject.getLabel() + " " + reportTypeLabel + " report", // Title of the panel displayed to the user
-                        vscode.ViewColumn.Two, // Open the panel in the second window
-                        {}, // Webview options
-                    );
-                    panel.webview.html = getReport(report); // display HTML content
-                } else {
-                    const message = localize("test.report.does.not.exist.run.test.first", report);
-                    vscode.window.showInformationMessage(message);
+            if(libProject.getContextValue() === LIBERTY_MAVEN_PROJECT || libProject.getContextValue() === LIBERTY_MAVEN_PROJECT_CONTAINER){
```
Comment (aparnamichael) [inline src/liberty/devCommands.ts:501]: Could you please add comments for the new lines of code? That would be helpful.

File: src/liberty/devCommands.ts [hunk 9]
```diff
@@ -490,28 +490,28 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+                console.log("report path ::"+report)
+                if(!await checkReportAndDisplay(report,reportType,reportTypeLabel,libProject)){
+                    report = getReportFile(path,"site",reportType+"-report.html");
```
Comment (aparnamichael) [inline src/liberty/devCommands.ts:504]: where are using this 'report'?

File: src/liberty/devCommands.ts (hunk 8 above)
Comment (JoshwinThomasIBM) [reply src/liberty/devCommands.ts:505]: added comments with the new commit , please [review](https://github.com/OpenLiberty/liberty-tools-vscode/pull/347/commits/e15319fc6708e0e9d74ef98debfa100e6680565b)

File: src/liberty/devCommands.ts [hunk 10]
```diff
@@ -610,4 +617,34 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
     return process.platform.startsWith("win");
-}
\ No newline at end of file
+}
+
+/*
+will return the path of the report, since there are diffrent folders to look into and the file names can be different 
+we need to get the paths to look for dynamically
+*/
+function getReportFile(path :any,dir :string,filename:string):any{
```
Comment (aparnamichael) [inline src/liberty/devCommands.ts:626]: Add space after comma and colon.
function getReportFile(path : any, dir :string, filename: string): any {

File: src/liberty/devCommands.ts [hunk 11]
```diff
@@ -610,4 +617,34 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
+    return Path.join(path,"target",dir, filename);
+}
+
+/*
+Function will check if the report is available within the given path and returns a boolean based on it and also 
+  the report will be displayed if it is available
+*/
+function checkReportAndDisplay(report : any,reportType : string,reportTypeLabel: string,libProject :LibertyProject): Promise<boolean> {
```
Comment (aparnamichael) [inline src/liberty/devCommands.ts:634]: Add space after comma and colon.

File: src/liberty/devCommands.ts (hunk 10 above)
Comment (JoshwinThomasIBM) [reply src/liberty/devCommands.ts]: Added spaces please see the changes in this [commit](https://github.com/JoshwinThomasIBM/liberty-tools-vscode/commit/327b975cf102358d31e8185180444adc9669afb2)

File: src/liberty/devCommands.ts (hunk 11 above)
Comment (JoshwinThomasIBM) [reply src/liberty/devCommands.ts]: Added spaces , changes are [here](https://github.com/JoshwinThomasIBM/liberty-tools-vscode/commit/327b975cf102358d31e8185180444adc9669afb2)

File: src/liberty/devCommands.ts [hunk 12]
```diff
@@ -490,28 +490,35 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+                if(!await checkReportAndDisplay(report,reportType,reportTypeLabel,libProject)){
+                    report = getReportFile(path,"site",reportType+"-report.html");
+                    if(!await checkReportAndDisplay(report,reportType,reportTypeLabel,libProject)){
+                        const message = localize("test.report.does.not.exist.run.test.first", report);
+                        vscode.window.showInformationMessage(message);
+                    }     
                 }
-            });
+            /*
+            if its a gralde project, then check existance for the report in the path set and if not display prompt for its non existance
```
Comment (aparnamichael) [inline src/liberty/devCommands.ts:515]: correct the spelling of 'gradle'

File: src/liberty/devCommands.ts [hunk 13]
```diff
@@ -490,28 +490,35 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+            */
+            }else if(!await checkReportAndDisplay(report,reportType,reportTypeLabel,libProject)){
```
Comment (aparnamichael) [inline src/liberty/devCommands.ts]: Checking for the report and displaying a "no test report found" message is currently implemented in both Maven and Gradle. Could we move this duplicate code into "checkReportAndDisplay"? Additionally, we could add a condition so that if the report type is "Maven" and the path is "reports/", the message is not displayed.

Comment (JoshwinThomasIBM) [reply src/liberty/devCommands.ts]: Made the changes as suggested , please [review](https://github.com/JoshwinThomasIBM/liberty-tools-vscode/commit/4f54c54fd8367ecfa5a5a8ef21fed3d061ed306c)

**Review by aparnamichael — DISMISSED** [review]
Looks good!!

File: src/liberty/devCommands.ts [hunk 14]
```diff
@@ -490,28 +490,30 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
-                } else {
-                    const message = localize("test.report.does.not.exist.run.test.first", report);
-                    vscode.window.showInformationMessage(message);
+            /*
+            if its a maven project, check for the report in the initial path , else try for the alternate one and if it doesnt exist in both 
+            display a prompt for its non existance
+            */
+            if(libProject.getContextValue() === LIBERTY_MAVEN_PROJECT || libProject.getContextValue() === LIBERTY_MAVEN_PROJECT_CONTAINER){
+                console.log("report path ::"+report)
+                if(!await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, "reports")){
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:507]: Formatting

```suggestion
                if (!await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, "reports")) {
```

File: src/liberty/devCommands.ts [hunk 15]
```diff
@@ -490,28 +490,30 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+                    report = getReportFile(path, "site", reportType + "-report.html");
+                    await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, "site")
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:509]: Use semicolon to be consistent with the rest of the project

```suggestion
                    await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, "site");   
```

File: src/liberty/devCommands.ts [hunk 16]
```diff
@@ -490,28 +490,30 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+                if(!await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, "reports")){
+                    report = getReportFile(path, "site", reportType + "-report.html");
+                    await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, "site")     
                 }
-            });
+            /*
+            if its a gradle project, then check existance for the report in the path set and if not display prompt for its non existance
+            */
+            }else 
+                await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject,"")
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:515]: Use semicolon to be consistent with the rest of the project

```suggestion
                await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject,"");
```

File: src/liberty/devCommands.ts [hunk 17]
```diff
@@ -490,28 +490,30 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+                console.log("report path ::"+report)
+                if(!await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, "reports")){
+                    report = getReportFile(path, "site", reportType + "-report.html");
+                    await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, "site")     
                 }
-            });
+            /*
+            if its a gradle project, then check existance for the report in the path set and if not display prompt for its non existance
+            */
+            }else
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:514]: Formatting

```suggestion
            } else 
```

File: src/liberty/devCommands.ts [hunk 18]
```diff
@@ -610,4 +612,44 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
     return process.platform.startsWith("win");
-}
\ No newline at end of file
+}
+
+/*
+will return the path of the report, since there are diffrent folders to look into and the file names can be different 
+we need to get the paths to look for dynamically
+*/
+function getReportFile(path : any, dir : string, filename : string) : any{
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:621]: Formatting

```suggestion
function getReportFile(path : any, dir : string, filename : string) : any {
```

File: src/liberty/devCommands.ts [hunk 19]
```diff
@@ -610,4 +612,44 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
+}
+
+/*
+Function will check if the report is available within the given path and returns a boolean based on it and also 
+  the report will be displayed if it is available
+*/
+function checkReportAndDisplay(report : any, reportType : string, reportTypeLabel : string, libProject : LibertyProject, directory : string) : Promise<boolean> {
+    return new Promise((resolve) => {
+      fs.exists(report, (exists) => {
+        if(exists){
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:632]: Formatting

```suggestion
        if (exists) {
```

File: src/liberty/devCommands.ts [hunk 20]
```diff
@@ -610,4 +612,44 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
+                vscode.ViewColumn.Two, // Open the panel in the second window
+                {}, // Webview options
+            );
+            panel.webview.html = getReport(report); // display HTML content
+            /*
+            For maven projects we need to check for the report in 'reports' and 'site', we only need to show the message if it is not 
+            available in both the locations, below condition make sure to avoid the message when its a maven project and the directory 
+            is 'reports'
+            */ 
+        }else if(!((libProject.getContextValue() === LIBERTY_MAVEN_PROJECT || libProject.getContextValue() === LIBERTY_MAVEN_PROJECT_CONTAINER)
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:645]: Formatting

```suggestion
        } else if (!((libProject.getContextValue() === LIBERTY_MAVEN_PROJECT || libProject.getContextValue() === LIBERTY_MAVEN_PROJECT_CONTAINER) 
```

File: src/liberty/devCommands.ts [hunk 21]
```diff
@@ -610,4 +612,44 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
+                {}, // Webview options
+            );
+            panel.webview.html = getReport(report); // display HTML content
+            /*
+            For maven projects we need to check for the report in 'reports' and 'site', we only need to show the message if it is not 
+            available in both the locations, below condition make sure to avoid the message when its a maven project and the directory 
+            is 'reports'
+            */ 
+        }else if(!((libProject.getContextValue() === LIBERTY_MAVEN_PROJECT || libProject.getContextValue() === LIBERTY_MAVEN_PROJECT_CONTAINER) 
+                    && directory=="reports")){
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:646]: Formatting

```suggestion
                    && directory=="reports")) {
```

File: src/liberty/devCommands.ts [hunk 22]
```diff
@@ -610,4 +612,44 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
+
+                const message = localize("test.report.does.not.exist.run.test.first", report);
+                vscode.window.showInformationMessage(message);
+        }
+        console.log("report available::"+exists);
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:651]: Do we need this log statement? Same as above,  if you think it is useful, it is probably best as a debug statement.

File: src/liberty/devCommands.ts [hunk 23]
```diff
@@ -490,28 +490,30 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+                    await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, "site")     
                 }
-            });
+            /*
+            if its a gradle project, then check existance for the report in the path set and if not display prompt for its non existance
+            */
+            }else 
+                await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject,"")
+
         }
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:517]: Why does there need to be two sets of `if - else` statements in this section of code? Why not put all the maven related steps under the initial `if maven` check and then all the gradle steps under the `if gradle` check?

File: src/liberty/devCommands.ts (hunk 21 above)
Comment (TrevCraw) [inline src/liberty/devCommands.ts:646]: This `if` statement may not always apply. If the directory changes again or the order we check the files changes, or if gradle projects become involved, we have to reconsider the logic. Since the logic to know if we want the error message to be displayed or not is determined outside of this method, it might be better to have a boolean variable named `showErrorMessage` that is passed in when this method is called.

File: src/test/MavenTestDevModeActions.ts [hunk 24]
```diff
@@ -99,8 +99,10 @@ it('Run tests for sample maven project', async () => {
 it('start maven with options from liberty dashboard', async () => {      
     
   const reportPath = path.join(utils.getMvnProjectPath(),"target","site","failsafe-report.html");
-  const deleteReport = await utils.deleteReports(reportPath);
-  expect (deleteReport).to.be.true;
+  const alternateReportPath = path.join(utils.getMvnProjectPath(), "target", "reports", "failsafe.html"); // new path to scan for the reports 
+  let deleteReport = await utils.deleteReports(reportPath);
+  let deleteAlternateReport = await utils.deleteReports(alternateReportPath);
+  expect (deleteReport || deleteAlternateReport).to.be.true; // there should be a report available irrespective of the surefire versions we use , so either one needs to be true
```
Comment (TrevCraw) [inline src/test/MavenTestDevModeActions.ts:105]: I believe the intention behind deleting the reports here is to set up the test so that we can confirm that the report files are created later. That means that _both_ reports should be deleted or not exist at this point. Instead of an OR, this should be an AND.

File: src/test/MavenTestDevModeActions.ts [hunk 25]
```diff
@@ -129,8 +132,10 @@ it('start maven with options from liberty dashboard', async () => {
 it('start maven with history from liberty dashboard', async () => {  
 
   const reportPath = path.join(utils.getMvnProjectPath(),"target","site","failsafe-report.html");
-  const deleteReport = await utils.deleteReports(reportPath);
-  expect (deleteReport).to.be.true;  
+  const alternateReportPath = path.join(utils.getMvnProjectPath(), "target", "reports", "failsafe.html");
+  let deleteReport = await utils.deleteReports(reportPath);
+  let deleteAlternateReport = await utils.deleteReports(alternateReportPath);
+  expect (deleteReport || deleteAlternateReport).to.be.true;
```
Comment (TrevCraw) [inline src/test/MavenTestDevModeActions.ts:138]: Same as above, _both_ reports should be deleted or not exist at this point. Instead of an OR, this should be an AND.

**Review by TrevCraw — CHANGES_REQUESTED** [review]

File: src/test/MavenTestDevModeActions.ts (hunk 24 above)
Comment (JoshwinThomasIBM) [reply src/test/MavenTestDevModeActions.ts:105]: The reports can only be either in the directory 'reports' or in 'site' depending upon the version of the plugin we use , if  AND is used then it expects report in 'reports' and 'site' to be deleted  which will not happen as the report will only be in one location at this point. if its OR then it will be only expecting to delete the report that is available either from 'reports' or 'site' .

File: src/liberty/devCommands.ts (hunk 23 above)
Comment (JoshwinThomasIBM) [reply src/liberty/devCommands.ts]: The suggested changes are made and please check it [here](https://github.com/OpenLiberty/liberty-tools-vscode/pull/347/commits/1ce4ace8bb21950f9c7a95e05392961d71c774c8)

**Review by aparnamichael — DISMISSED** [review]

File: src/test/MavenTestDevModeActions.ts (hunk 24 above)
Comment (TrevCraw) [reply src/test/MavenTestDevModeActions.ts:105]: OK, let's take a step back and look at the `deleteReports()` function and what it is doing:
https://github.com/JoshwinThomasIBM/liberty-tools-vscode/blob/issue340fix/src/test/utils/testUtils.ts#L66-L81

- The first thing it does is check to see if `reportPath` exists. If it does _not_ exist, the method returns `true`, since the report is not there. The report does not have to be deleted for this function to return `true`. It can just not exist.
- If `reportPath` does exist, the function attempts to delete the file at the location of `reportPath`. If deletion succeeds, it returns `true` and if deletion fails, it returns `false`.

So now going back to the new code added. Let's assume that the tests are using the latest LMP and that test reports are being generated to the "reports" dir. The value of `deleteReport` after calling `deleteReports()` and passing in the "site" dir path will be `true`, since the report does not exist at the "site" dir.  Now, for `deleteAlternateReport`, the code calls `deleteReports()` and passes the "reports" dir path. Let's assume there is a problem with the filesystem and deleting the report fails. That means `deleteReports()` would return `false`.

On the next line where the test runs `expect`, we would expect the test to fail. The test is invalid if we continue on and a test report already exists. However, using an OR statement will not fail the test on this line and the test will run in an invalid state. On the other hand, using an AND would catch this problem and fail the test on this line as expected.

Essentially, because the `deleteReports()` method returns `true` if the report is deleted or did not exist in the first place, we should be using an AND operator. We want both reports to not exist when going into these tests.

File: src/liberty/devCommands.ts [hunk 26]
```diff
@@ -77,18 +77,17 @@ export async function openProject(pomPath: string): Promise<void> {
...
+            return;
+        }
+        const command = COMMAND_TITLES.get(selection);
+        if (command !== undefined) {
+            vscode.commands.executeCommand(command);
+        } else {
+            // should never happen
+            console.error("Unable to find corresponding command for " + selection);
+        }
+
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:90]: Please do not do any formatting changes to code that is not added or modified by you for this PR. It makes the changes in the PR more difficult to follow. To fix formatting in existing code, we should open separate PRs that are specifically for fixing formatting.

For instance, reviewing this section, it is not immediately clear to me if there was a functional change here or not.

File: src/liberty/devCommands.ts [hunk 27]
```diff
@@ -130,7 +129,7 @@ export async function startDevMode(libProject?: LibertyProject | undefined): Pro
 
 export async function removeProject(): Promise<void> {
     const projectProvider: ProjectProvider = ProjectProvider.getInstance();
-    
+
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:132]: Please do not do any formatting changes to code that is not added or modified by you for this PR.

File: src/liberty/devCommands.ts [hunk 28]
```diff
@@ -163,7 +162,7 @@ export async function removeProject(): Promise<void> {
                     }
                 });
         });
-        
+
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:165]: Please do not do any formatting changes to code that is not added or modified by you for this PR.

File: src/liberty/devCommands.ts [hunk 29]
```diff
@@ -193,11 +192,11 @@ export async function addProject(uri: vscode.Uri): Promise<void> {
         // scan the folder and get a list of folders with pom.xml and build.gradle
         const uris: string[] = await projectProvider.getListOfMavenAndGradleFolders(uri.fsPath);
         console.log(JSON.stringify(uris));
-        if ( uris.length > 0) {
+        if (uris.length > 0) {
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:195]: Please do not do any formatting changes to code that is not added or modified by you for this PR.

File: src/liberty/devCommands.ts [hunk 30]
```diff
@@ -193,11 +192,11 @@ export async function addProject(uri: vscode.Uri): Promise<void> {
...
             // present the list to add
             showListOfPathsToAdd(uris);
         }
-        
+
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:199]: Please do not do any formatting changes to code that is not added or modified by you for this PR.

File: src/liberty/devCommands.ts [hunk 31]
```diff
@@ -399,7 +398,7 @@ export async function customDevMode(libProject?: LibertyProject | undefined, par
             if (customCommand !== undefined) {
                 // save command
                 customCommand = customCommand.trim();
-                if ( customCommand.length > 0 ) {
+                if (customCommand.length > 0) {
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:401]: Please do not do any formatting changes to code that is not added or modified by you for this PR.

File: src/liberty/devCommands.ts [hunk 32]
```diff
@@ -489,29 +488,25 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+                    showErrorMessage = true;//report is not available in 'reports', hence show the message if report is not availabe in 'site', so setting to true
+                    await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, showErrorMessage);
                 }
-            });
+            } else if (libProject.getContextValue() === LIBERTY_GRADLE_PROJECT || libProject.getContextValue() === LIBERTY_GRADLE_PROJECT_CONTAINER) {
+                report = await getGradleTestReport(libProject.path, path);
+                await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, showErrorMessage);
+            }
+
+
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:509]: Formatting
```suggestion
```

File: src/liberty/devCommands.ts [hunk 33]
```diff
@@ -610,4 +605,42 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
+                    {}, // Webview options
+                );
+                panel.webview.html = getReport(report); // display HTML content
+                /*
+                For maven projects we need to check for the report in 'reports' and 'site', we only need to show the message if it is not 
+                available in both the locations, below condition make sure to avoid the message when its a maven project and the directory 
+                is 'reports'
+                */
+            } else if (showErrorMessage) {// if it is flagged to show the error message then show it else dont
+
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:639]: Formatting
```suggestion
```

**Review by TrevCraw — CHANGES_REQUESTED** [review]

File: src/test/MavenTestDevModeActions.ts (hunk 24 above)
Comment (JoshwinThomasIBM) [reply src/test/MavenTestDevModeActions.ts]: Understood , the changes are made as suggested

File: src/liberty/devCommands.ts (hunk 26 above)
Comment (JoshwinThomasIBM) [reply src/liberty/devCommands.ts]: Understood , removed the formatting which is not part of this PR

**Review by aparnamichael — APPROVED** [review]

File: src/test/MavenTestDevModeActions.ts [hunk 34]
```diff
@@ -99,8 +99,10 @@ it('Run tests for sample maven project', async () => {
 it('start maven with options from liberty dashboard', async () => {      
     
   const reportPath = path.join(utils.getMvnProjectPath(),"target","site","failsafe-report.html");
-  const deleteReport = await utils.deleteReports(reportPath);
-  expect (deleteReport).to.be.true;
+  const alternateReportPath = path.join(utils.getMvnProjectPath(), "target", "reports", "failsafe.html"); // new path to scan for the reports 
+  let deleteReport = await utils.deleteReports(reportPath);
+  let deleteAlternateReport = await utils.deleteReports(alternateReportPath);
+  expect (deleteReport && deleteAlternateReport).to.be.true; // there should be a report available irrespective of the surefire versions we use , so either one needs to be true
```
Comment (TrevCraw) [inline src/test/MavenTestDevModeActions.ts:105]:
```suggestion
  expect (deleteReport && deleteAlternateReport).to.be.true; // both report files should either not exist or be successfully deleted
```

File: src/test/MavenTestDevModeActions.ts [hunk 35]
```diff
@@ -129,8 +132,10 @@ it('start maven with options from liberty dashboard', async () => {
 it('start maven with history from liberty dashboard', async () => {  
 
   const reportPath = path.join(utils.getMvnProjectPath(),"target","site","failsafe-report.html");
-  const deleteReport = await utils.deleteReports(reportPath);
-  expect (deleteReport).to.be.true;  
+  const alternateReportPath = path.join(utils.getMvnProjectPath(), "target", "reports", "failsafe.html");
+  let deleteReport = await utils.deleteReports(reportPath);
+  let deleteAlternateReport = await utils.deleteReports(alternateReportPath);
+  expect (deleteReport && deleteAlternateReport).to.be.true;
```
Comment (TrevCraw) [inline src/test/MavenTestDevModeActions.ts:138]:
```suggestion
  expect (deleteReport && deleteAlternateReport).to.be.true;  // both report files should either not exist or be successfully deleted
```

File: src/test/MavenTestDevModeActions.ts [hunk 36]
```diff
@@ -111,7 +113,8 @@ it('start maven with options from liberty dashboard', async () => {
   {
     console.log("Server succuessfully started");  
     let checkFile = await utils.checkIfTestReportExists(reportPath);
-    expect (checkFile).to.be.true;
+    let checkAlternateFile = await utils.checkIfTestReportExists(alternateReportPath);
+    expect (checkFile || checkAlternateFile).to.be.true;
```
Comment (TrevCraw) [inline src/test/MavenTestDevModeActions.ts:117]:
```suggestion
    expect (checkFile || checkAlternateFile).to.be.true; // check both potential locations for the test report, one of them must exist
```

File: src/test/MavenTestDevModeActions.ts [hunk 37]
```diff
@@ -142,7 +147,8 @@ it('start maven with history from liberty dashboard', async () => {
...
```
Comment (TrevCraw) [inline src/test/MavenTestDevModeActions.ts:151]:
```suggestion
    expect (checkFile || checkAlternateFile).to.be.true; // check both potential locations for the test report, one of them must exist
```

File: src/liberty/devCommands.ts [hunk 38]
```diff
@@ -489,29 +489,24 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+                    report = getReportFile(path, "site", reportType + "-report.html");
+                    showErrorMessage = true;//report is not available in 'reports', hence show the message if report is not availabe in 'site', so setting to true
+                    await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, showErrorMessage);
                 }
-            });
+            } else if (libProject.getContextValue() === LIBERTY_GRADLE_PROJECT || libProject.getContextValue() === LIBERTY_GRADLE_PROJECT_CONTAINER) {
+                report = await getGradleTestReport(libProject.path, path);
+                await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, showErrorMessage);
+            }
+
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:509]:
```suggestion
```

File: src/liberty/devCommands.ts [hunk 39]
```diff
@@ -489,29 +489,24 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
-                        {}, // Webview options
-                    );
-                    panel.webview.html = getReport(report); // display HTML content
-                } else {
-                    const message = localize("test.report.does.not.exist.run.test.first", report);
-                    vscode.window.showInformationMessage(message);
+            let showErrorMessage: boolean = true;
+            if (libProject.getContextValue() === LIBERTY_MAVEN_PROJECT || libProject.getContextValue() === LIBERTY_MAVEN_PROJECT_CONTAINER) {
+                report = getReportFile(path, "reports", reportType + ".html");
+                showErrorMessage = false; // show the error message only if the directory is not reports, so setting to false
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:499]:
```suggestion
                showErrorMessage = false; // show the error message only if both "reports" and "site" locations do not contain the test reports - setting to false since this will be the first location checked
```

File: src/liberty/devCommands.ts [hunk 40]
```diff
@@ -489,29 +489,24 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+                if (!await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, showErrorMessage)) {
+                    report = getReportFile(path, "site", reportType + "-report.html");
+                    showErrorMessage = true;//report is not available in 'reports', hence show the message if report is not availabe in 'site', so setting to true
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:502]:
```suggestion
                    showErrorMessage = true; // // show the error message only if both "reports" and "site" locations do not contain the test reports - setting to true since this will be the second location checked
```

File: src/liberty/devCommands.ts [hunk 41]
```diff
@@ -610,4 +605,41 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
+                    vscode.ViewColumn.Two, // Open the panel in the second window
+                    {}, // Webview options
+                );
+                panel.webview.html = getReport(report); // display HTML content
+                /*
+                For maven projects we need to check for the report in 'reports' and 'site', we only need to show the message if it is not 
+                available in both the locations, below condition make sure to avoid the message when its a maven project and the directory 
+                is 'reports'
+                */
+            } else if (showErrorMessage) {// if it is flagged to show the error message then show it else dont
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:638]:
```suggestion
            } else if (showErrorMessage) { // if it is flagged to show the error message, then show it; otherwise do not show it
```

File: src/liberty/devCommands.ts [hunk 42]
```diff
@@ -489,29 +489,23 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
-                        {}, // Webview options
-                    );
-                    panel.webview.html = getReport(report); // display HTML content
-                } else {
-                    const message = localize("test.report.does.not.exist.run.test.first", report);
-                    vscode.window.showInformationMessage(message);
+            let showErrorMessage: boolean = true;
+            if (libProject.getContextValue() === LIBERTY_MAVEN_PROJECT || libProject.getContextValue() === LIBERTY_MAVEN_PROJECT_CONTAINER) {
+                report = getReportFile(path, "reports", reportType + ".html");
+                showErrorMessage = false; // show the error message only if both "reports" and "site" dirs do not contain the test reports - setting to false since this will be the first location checked
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:499]:
```suggestion
                // show the error message only if both "reports" and "site" dirs do not contain the test reports
                // set to false since this will be the first location checked
                showErrorMessage = false; 
```

File: src/liberty/devCommands.ts [hunk 43]
```diff
@@ -489,29 +489,23 @@ export async function openReport(reportType: string, libProject?: LibertyProject
...
+                if (!await checkReportAndDisplay(report, reportType, reportTypeLabel, libProject, showErrorMessage)) {
+                    report = getReportFile(path, "site", reportType + "-report.html");
+                    showErrorMessage = true; // show the error message only if both "reports" and "site" dirs do not contain the test reports - setting to true since this will be the second location checked
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:502]:
```suggestion
                    // show the error message only if both "reports" and "site" dirs do not contain the test reports
                    // set to true since this will be the second location checked
                    showErrorMessage = true; 
```

File: src/liberty/devCommands.ts [hunk 44]
```diff
@@ -610,4 +604,41 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
+                    reportType, // Identifies the type of the webview. Used internally
+                    libProject.getLabel() + " " + reportTypeLabel + " report", // Title of the panel displayed to the user
+                    vscode.ViewColumn.Two, // Open the panel in the second window
+                    {}, // Webview options
+                );
+                panel.webview.html = getReport(report); // display HTML content
+                /*
+                For maven projects we need to check for the report in 'reports' and 'site', we only need to show the message if it is not 
+                available in both the locations, below condition make sure to avoid the message when its a maven project and the directory 
+                is 'reports'
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:635]:
```suggestion
                For Maven projects we need to check for the test report in 'reports' and 'site' dirs. 
                We only need to show the message if it is not available in both locations. 
                The `showErrorMessage` flag will only be set to true when checking the second location.
```

File: src/liberty/devCommands.ts [hunk 45]
```diff
@@ -610,4 +604,41 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
...
+                */
+            } else if (showErrorMessage) { // If it is flagged to show the error message, then show it. Otherwise do not show it.
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:637]:
```suggestion
            } else if (showErrorMessage) {
```

**Review by TrevCraw — APPROVED** [review]

**Review by aparnamichael — APPROVED** [review]
