### PR TITLE
Fixes #264 - Fixes for manually added projects not being listed in the dashboard after re-opening IDE or workspace

### LINKED ISSUE #264: Manually added project to dashboard is removed after re-opening workspace or re-opening IDE
**Problem:**
A project manually added to the Liberty Dashboard is removed from the the Liberty Dashboard after the workspace is closed and re-opened or if the IDE is closed and re-opened.
The issue occurs If the workspace has more than two projects, and it tends to happen only the first time the sequence of steps outlined below are followed. Subsequent attempts to remove/add the project in question and re-open the workspace/IDE work as expected: The added project is still listed in the Liberty Dashboard after the workspace is re-opened.

**Steps to recreate:**

1. Created a Gradle abd Maven starter projects (https://openliberty.io/start/)

2. Open the Gradle project (file→ Open Folder).

3. Add the Maven project to the workspace (File-> Add Folder to workspace)

4. Expand the Gradle project:

-  Rename src/main/liberty/config to src/main/liberty/config2

- Comment out the Liberty Gradle Plugin definition entry in build.gradle and save:

```
plugins {

    id 'war'

    // id 'io.openliberty.tools.gradle.Liberty' version '3.6.1'

}
```

The gradle project should have been removed.

5. Right click on project explorer, and select: 

“Add Project to Liberty Dashboard”.

Select the Gradle project. The project should now be added to the Liberty dashboard.

6. Go to File -> “Close Workspace”.

7. When asked: “Do you want to save your workspace configuration as a file?”

Select save, specify the dir and file name + save.

8. Go to File-> “Open Workspace from file” and select the file previously saved.

### PR DESCRIPTION
**Pull request by JoshwinThomasIBM**
Fixes #264 Changes include the user being asked for saving the workspace when they try to add a project to the dashboard manually

### CODE REVIEW

File: src/liberty/libertyProject.ts [hunk 1]
```diff
@@ -203,6 +203,47 @@ export class ProjectProvider implements vscode.TreeDataProvider<LibertyProject>
...
+		});
+	}
+
+	/*
+	Method identifies a workspace that is untitled and containing more than one project 
+	*/
+	public isUntitledWorkspace(): boolean {
+		const workspaceFolders = vscode.workspace.workspaceFolders;
+		if ((workspaceFolders && workspaceFolders.length > 1
+			&& vscode.workspace.name === "Untitled (Workspace)")) {
```
Comment (aparnamichael) [inline src/liberty/libertyProject.ts:241]: Please move this "Untitled (Workspace)'' to some constants file.

File: src/liberty/devCommands.ts [hunk 2]
```diff
@@ -610,4 +615,14 @@ async function getLocalGradleWrapper(projectFolder: string): Promise<string | un
  */
 function isWin(): boolean {
     return process.platform.startsWith("win");
+}
+/*
```
[the remark this answers is not in the document]
Comment (JoshwinThomasIBM) [reply src/liberty/devCommands.ts:623]: Added

File: src/liberty/libertyProject.ts [hunk 3]
```diff
@@ -203,6 +203,47 @@ export class ProjectProvider implements vscode.TreeDataProvider<LibertyProject>
 		statusMessage.dispose();
 	}
 
+	/*
+	Method asks the user to save the workspace first if it is untitled and the workspace contains morethan
```
[the remark this answers is not in the document]
Comment (JoshwinThomasIBM) [reply src/liberty/libertyProject.ts]: Made the changes for multi line comments

File: src/liberty/libertyProject.ts (hunk 1 above)
Comment (JoshwinThomasIBM) [reply src/liberty/libertyProject.ts]: Moved to constants.ts

File: src/liberty/libertyProject.ts [hunk 4]
```diff
@@ -14,7 +14,7 @@ import * as gradleUtil from "../util/gradleUtil";
 import * as mavenUtil from "../util/mavenUtil";
 import * as util from "../util/helperUtil";
 import { localize } from "../util/i18nUtil";
-import { EXCLUDED_DIR_PATTERN, LIBERTY_GRADLE_PROJECT, LIBERTY_GRADLE_PROJECT_CONTAINER, LIBERTY_MAVEN_PROJECT, LIBERTY_MAVEN_PROJECT_CONTAINER } from "../definitions/constants";
+import { EXCLUDED_DIR_PATTERN, LIBERTY_GRADLE_PROJECT, LIBERTY_GRADLE_PROJECT_CONTAINER, LIBERTY_MAVEN_PROJECT, LIBERTY_MAVEN_PROJECT_CONTAINER,UNTITLED_WORKSPACE } from "../definitions/constants";
```
Comment (TrevCraw) [inline src/liberty/libertyProject.ts:17]: Formatting
```suggestion
import { EXCLUDED_DIR_PATTERN, LIBERTY_GRADLE_PROJECT, LIBERTY_GRADLE_PROJECT_CONTAINER, LIBERTY_MAVEN_PROJECT, LIBERTY_MAVEN_PROJECT_CONTAINER, UNTITLED_WORKSPACE } from "../definitions/constants";
```

File: src/liberty/libertyProject.ts [hunk 5]
```diff
@@ -203,6 +203,49 @@ export class ProjectProvider implements vscode.TreeDataProvider<LibertyProject>
...
+			} catch (error) {
+				console.debug("exception while saving the workspace" + error);
+			}
+		});
+	}
+
+	/*
+	Method identifies a workspace that is untitled and containing more than one project 
+	*/
+	public isUntitledWorkspace(): boolean {
```
Comment (TrevCraw) [inline src/liberty/libertyProject.ts:240]:
```suggestion
	public isMultiProjectUntitledWorkspace(): boolean {
```

File: src/liberty/devCommands.ts [hunk 6]
```diff
@@ -173,10 +173,18 @@ function showListOfPathsToAdd(uris: string[]) {
         if (!selection) {
             return;
         }
-        const result = await projectProvider.addUserSelectedPath(selection, projectProvider.getProjects());
-        const message = localize(`add.project.manually.message.${result}`, selection);
-        (result !== 0) ? console.error(message) : console.info(message); projectProvider.fireChangeEvent();
-        vscode.window.showInformationMessage(message);
+        if (projectProvider.isUntitledWorkspace()) {
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:176]:
```suggestion
        if (projectProvider.isMultiProjectUntitledWorkspace()) {
```

File: src/liberty/devCommands.ts [hunk 7]
```diff
@@ -173,10 +173,18 @@ function showListOfPathsToAdd(uris: string[]) {
...
+            /**
+             * Saving the selected project to globalstate for adding it to the dashboard after 
+             * reinitialization of the extension when workspace is saved
+             */
+            await projectProvider.getContext().globalState.update('selectedProject', selection);
```
Comment (TrevCraw) [inline src/liberty/devCommands.ts:181]: One of the things discussed with this issue was the limitation of adding more than one project to the dashboard when a user saves the workspace. This is not required for this PR, but would it not possible to use an array here instead of just a string object? Then all added projects can be saved to the workspace.

File: src/liberty/libertyProject.ts [hunk 8]
```diff
@@ -203,6 +203,49 @@ export class ProjectProvider implements vscode.TreeDataProvider<LibertyProject>
...
+					resolve();
+				});
+			} catch (error) {
+				console.debug("exception while saving the workspace" + error);
+			}
+		});
+	}
+
+	/*
+	Method identifies a workspace that is untitled and containing more than one project
```
Comment (TrevCraw) [inline src/liberty/libertyProject.ts:238]:
```suggestion
	Method identifies a workspace that is untitled and contains more than one project 
```

File: src/liberty/libertyProject.ts [hunk 9]
```diff
@@ -203,6 +203,49 @@ export class ProjectProvider implements vscode.TreeDataProvider<LibertyProject>
...
+	/**
+	 * Method asks the user to save the workspace first if it is untitled and the workspace contains morethan
+	 * one project. if not saved there are chances for the projects state not being saved and manually added
+	 * projects might not be visible in the liberty dashboard.
+	 */
+	public async checkUntitledWorkspaceAndSaveIt(): Promise<void> {
+		return new Promise((resolve) => {
+			try {
+				vscode.window.showInformationMessage(
+					'Please save the workspace first, as manually added projects to the dashboard may not persist in the next VS Code session if the workspace is not saved.',
```
Comment (TrevCraw) [inline src/liberty/libertyProject.ts:215]: Suggestion for rewording is below, but please also move this message to https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/src/locales/en.json.
```suggestion
					'Please save the workspace first. Projects that are manually added to the Liberty dashboard may not persist in the next VS Code session if the workspace is not saved before adding the project.',
```

File: src/liberty/libertyProject.ts [hunk 10]
```diff
@@ -203,6 +203,49 @@ export class ProjectProvider implements vscode.TreeDataProvider<LibertyProject>
...
+					if (selection === 'Save Workspace') {
+						/**
+						 * setting workspaceSaveInProgress to true and storing it in globalstate for identifyting that the
+						 * workspace is saved and needs to save the manually added projects to the dashboard
+						 */
+						await this._context.globalState.update('workspaceSaveInProgress', true);
+						//opens the saveWorkspace as dialog box
+						await vscode.commands.executeCommand('workbench.action.saveWorkspaceAs');
+					}
+					util.clearDataSavedInGlobalState(this._context);
```
Comment (TrevCraw) [inline src/liberty/libertyProject.ts:228]: It seems like this line is executed when a user cancels. Could you explain why we need to clear the global state data when a user cancels? It might be good to add a comment to explain.

File: src/liberty/libertyProject.ts [hunk 11]
```diff
@@ -203,6 +203,49 @@ export class ProjectProvider implements vscode.TreeDataProvider<LibertyProject>
...
+					resolve();
+				});
+			} catch (error) {
+				console.debug("exception while saving the workspace" + error);
```
Comment (TrevCraw) [inline src/liberty/libertyProject.ts:232]: if there is an error during saving, should we clear the global state data at this point too?

File: src/liberty/libertyProject.ts [hunk 12]
```diff
@@ -203,6 +203,49 @@ export class ProjectProvider implements vscode.TreeDataProvider<LibertyProject>
 		statusMessage.dispose();
 	}
 
+	/**
+	 * Method asks the user to save the workspace first if it is untitled and the workspace contains morethan
+	 * one project. if not saved there are chances for the projects state not being saved and manually added
+	 * projects might not be visible in the liberty dashboard.
```
Comment (TrevCraw) [inline src/liberty/libertyProject.ts:209]:
```suggestion
	 * This method asks the user to save the workspace first if it is untitled and the workspace contains more than
	 * one project. If not saved, there are chances that the project's state may not be saved and manually added
	 * projects may not be visible in the Liberty dashboard in a new VS Code session.
```

File: src/util/helperUtil.ts [hunk 13]
```diff
@@ -71,4 +71,12 @@ export function getStorageData(context: vscode.ExtensionContext): DashboardData
...
 	await context.workspaceState.update(LIBERTY_DASHBOARD_WORKSPACE_STORAGE_KEY, dasboardData);
 }
+/**
+ * clears the states saved in global state
+ * @param context 
+ */
+export function clearDataSavedInGlobalState(context: vscode.ExtensionContext) {
+	context.globalState.update('workspaceSaveInProgress', false);
+	context.globalState.update('selectedProject', undefined);
+}
```
Comment (TrevCraw) [inline src/util/helperUtil.ts:81]: please update copyright date as well

**Review by TrevCraw — CHANGES_REQUESTED** [review]

File: src/liberty/libertyProject.ts (hunk 10 above)
Comment (JoshwinThomasIBM) [reply src/liberty/libertyProject.ts:228]: The user can choose to close the workspace or IDE without saving and have the data still in global state . since global state is common to all the Vs code instances if not cleared there is a chance to use this data and add it into the dashboard of different Vs code sessions

File: src/liberty/devCommands.ts (hunk 7 above)
Comment (JoshwinThomasIBM) [reply src/liberty/devCommands.ts:181]: Yes we can use an array/Set here , but then we would need to handle few cases 
where the user might add/remove projects from dashboard and update the set accordingly , or after making all the changes the user can close the workspace/IDE without saving . and we should clear the data from global state once a Vs code session is closed (Both closing the IDE and workspace scenarios), else this data will be available for other vs code sessions / workspaces and there are chances for wrong projects getting added in different vscode workspaces  .
 Since we have not yet found a way to hook into the flow when user chooses file->close workspace we might not be able to clear the global state here ,  i think it would be good to make these changes ( using a set or an array here and handling the above cases ) along with #386

File: src/liberty/libertyProject.ts (hunk 11 above)
Comment (JoshwinThomasIBM) [reply src/liberty/libertyProject.ts:239]: Yes , cleared the global state

File: src/definitions/constants.ts [hunk 14]
```diff
@@ -34,6 +34,7 @@ export const COMMAND_AND_PROJECT_TYPE_MAP: { [command: string]: string[] } = {
 };
 export const EXCLUDED_DIR_PATTERN = "**/{bin,classes,target}/**";
 export const COMMAND_TITLES = new Map();
+export const UNTITLED_WORKSPACE="Untitled (Workspace)";
```
[the remark this answers is not in the document]
Comment (JoshwinThomasIBM) [reply src/definitions/constants.ts:37]: Done

File: src/liberty/libertyProject.ts (hunk 9 above)
Comment (JoshwinThomasIBM) [reply src/liberty/libertyProject.ts]: Message is corrected and is moved as suggested

File: src/liberty/libertyProject.ts (hunk 5 above)
Comment (JoshwinThomasIBM) [reply src/liberty/libertyProject.ts]: Renamed the method to the suggested name

File: src/liberty/devCommands.ts (hunk 6 above)
Comment (JoshwinThomasIBM) [reply src/liberty/devCommands.ts]: References are also updated

File: src/liberty/libertyProject.ts (hunk 4 above)
Comment (JoshwinThomasIBM) [reply src/liberty/libertyProject.ts]: Corrected

File: src/extension.ts [hunk 15]
```diff
@@ -109,7 +110,11 @@ function registerCommands(context: ExtensionContext) {
 		projectProvider = new ProjectProvider(context);
 		ProjectProvider.setInstance(projectProvider);
 	}
-
+    if (projectProvider.getContext().globalState.get('workspaceSaveInProgress') &&
+        projectProvider.getContext().globalState.get('selectedProject') !== undefined) {
+        devCommands.addProjectsToTheDashBoard(projectProvider, projectProvider.getContext().globalState.get('selectedProject') as string);
+        helperUtil.clearDataSavedInGlobalState(projectProvider.getContext());
+    }
```
[the remark this answers is not in the document]
Comment (JoshwinThomasIBM) [reply src/extension.ts]: Moved the above code to a method and called as suggested

File: src/liberty/libertyProject.ts (hunk 12 above)
Comment (JoshwinThomasIBM) [reply src/liberty/libertyProject.ts]: Formatted and corrected the comment

**Review by aparnamichael — APPROVED** [review]

File: src/liberty/devCommands.ts (hunk 7 above)
Comment (TrevCraw) [reply src/liberty/devCommands.ts:176]: Can you open an enhancement issue to address these scenarios?

File: src/extension.ts (hunk 15 above)
[the remark this answers is not in the document]
Comment (TrevCraw) [reply src/extension.ts]: Thank you for moving the code to its own method. The second part of the suggestion was to make this call outside of the `registerCommands` method, since it does not belong in this method. The call to the new method `handleWorkspaceSaveInProgress` should be made from the `activate` method.

File: src/liberty/dashboard.ts [hunk 16]
```diff
@@ -1,5 +1,5 @@
 /**
- * Copyright (c) 2022 IBM Corporation.
+ * Copyright (c) 2024 IBM Corporation.
```
Comment (TrevCraw) [inline src/liberty/dashboard.ts:2]: Why did you update this copyright if there are no changes in this file?

File: src/liberty/libertyProject.ts [hunk 17]
```diff
@@ -203,6 +203,56 @@ export class ProjectProvider implements vscode.TreeDataProvider<LibertyProject>
...
+					 * which is shared across all VS Code instances. To prevent this data from being mistakenly used in other 
+					 * sessions and added to the dashboard, it should be cleared if the user cancels the save.
+					 */
+					util.clearDataSavedInGlobalState(this._context);
+					resolve();
+				});
+			} catch (error) {
+				util.clearDataSavedInGlobalState(this._context);
+				resolve();
+				console.debug("exception while saving the workspace" + error);
```
Comment (TrevCraw) [inline src/liberty/libertyProject.ts:239]: In scenarios like this, it is typically good practice to place the debug statement first before calling other methods just in case those methods run into other problems. That way you at least know you entered this code block.

**Review by TrevCraw — CHANGES_REQUESTED** [review]

File: src/liberty/libertyProject.ts (hunk 17 above)
Comment (JoshwinThomasIBM) [reply src/liberty/libertyProject.ts]: rearranged the code

File: src/liberty/dashboard.ts (hunk 16 above)
Comment (JoshwinThomasIBM) [reply src/liberty/dashboard.ts]: Reverted this change

File: src/liberty/devCommands.ts (hunk 7 above)
Comment (JoshwinThomasIBM) [reply src/liberty/devCommands.ts:176]: Sure @TrevCraw

File: src/extension.ts (hunk 15 above)
[the remark this answers is not in the document]
Comment (JoshwinThomasIBM) [reply src/extension.ts]: handleWorkspaceSaveInProgress requires projectProvider as a parameter and i see we have code for getting the instance for projectProvider within the registerCommands methods , thats why i left handleWorkspaceSaveInProgress within registerCommands

[the remark this answers is not in the document]
Comment (JoshwinThomasIBM) [reply src/extension.ts]: moved the handleWorkspaceSaveInProgress to activate, please review

File: src/extension.ts [hunk 18]
```diff
@@ -62,7 +63,7 @@ export async function activate(context: vscode.ExtensionContext): Promise<void>
             item.text = localize("liberty.ls.thumbs.up");
             item.tooltip = localize("liberty.ls.started");
             toggleItem(window.activeTextEditor, item);
-    
+            handleWorkspaceSaveInProgress(getProjectProvider(context));
```
Comment (aparnamichael) [inline src/extension.ts:66]: @JoshwinThomasIBM Instead of passing 'getProjectProvider(context)'  as a parameter, can we call this method directly inside `handleWorkspaceSaveInProgress`, similar to how it is done in `registerCommands`?

Comment (JoshwinThomasIBM) [reply src/extension.ts:66]: you mean to  call handleWorkspaceSaveInProgress by passing context as parameter and inside handleWorkspaceSaveInProgress get the project provider instance ?

Comment (aparnamichael) [reply src/extension.ts]: yes

Comment (JoshwinThomasIBM) [reply src/extension.ts]: Changes are done as suggested

**Review by aparnamichael — APPROVED** [review]

**Review by TrevCraw — APPROVED** [review]
Looks good! Please open an issue for what was discussed in this thread: https://github.com/OpenLiberty/liberty-tools-vscode/pull/372#discussion_r1853105648. Make sure to reference that thread in the issue. Thanks!

**Comment by JoshwinThomasIBM** [comment]
Created the issues for the discussed ones - [394](https://github.com/OpenLiberty/liberty-tools-vscode/issues/394),[395](https://github.com/OpenLiberty/liberty-tools-vscode/issues/395),[396](https://github.com/OpenLiberty/liberty-tools-vscode/issues/396)
