### PR TITLE
fix #187 test report path incorrect

### LINKED ISSUE #187: Path not correct for retrieving VS Code test report
For example, using the MicroProfile health guide project (https://github.com/OpenLiberty/guide-microprofile-health)

- right-click, start
- right-click, run tests - integration tests run
- right-click, view integration test report - hit the error below - it is missing the `finish` directory

image

It appears this line of code is the culprit:
https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/src/liberty/devCommands.ts#L492

### PR DESCRIPTION
**Pull request by travis1111**

### CODE REVIEW

File: src/util/gradleUtil.ts [hunk 1]
```diff
@@ -142,7 +142,7 @@ export function findChildGradleProjects(buildFile: any, settingsFile: any): Grad
  * @param gradlePath build.gradle file
  * @param workspaceFolder workspace of current project
  */
-export async function getGradleTestReport(gradlePath: any, workspaceFolder: vscode.WorkspaceFolder): Promise<string> {
+export async function getGradleTestReport(gradlePath: any, workspaceFolder: string): Promise<string> {
```
Comment (kathrynkodama) [inline src/util/gradleUtil.ts:145]: Should rename this variable from `workspaceFolder` to something more appropriate now that we aren't using `vscode.WorkspaceFolder`. Same comment applies to `findCustomTestReport` and `helperUtil` methods below

Comment (travis1111) [reply src/util/gradleUtil.ts]: done

**Review by kathrynkodama — APPROVED** [review]
