### PR TITLE
Archive screenshots in GHA

### LINKED ISSUE #441: Investigate how to get videos/screenshots of failed tests in GHA using VScode extension tester
Investigate how to get videos/screenshots of failed tests in GHA using VScode extension tester.
https://github.com/redhat-developer/vscode-extension-tester

### PR DESCRIPTION
**Pull request by gilbysunil14**
Created a new step in the workflow to archive screenshots.

Fixes #441

### CODE REVIEW

File: src/test/MavenTestDevModeActions.ts [hunk 1]
```diff
@@ -269,6 +270,39 @@ it('attach debugger for start with custom parameter event', async () => {
     
 }).timeout(350000);
```
Comment (aparnamichael) [inline src/test/MavenTestDevModeActions.ts:272]: Please add a comment here explaining the purpose of this after hook and reason for adding after hook here..

File: src/test/MavenTestDevModeActions.ts [hunk 2]
```diff
@@ -269,6 +270,39 @@ it('attach debugger for start with custom parameter event', async () => {
...
 
+  after(() => {
+    const sourcePath = VSBrowser.instance.getScreenshotsDir();
+    const destinationPath = './screenshots';
+
+    copyFolderContents(sourcePath, destinationPath);
+  });
+
+  function copyFolderContents(sourceFolder: string, destinationFolder: string): void {
+    console.log('source folder', sourceFolder);
```
Comment (aparnamichael) [inline src/test/MavenTestDevModeActions.ts:281]: Remove unneccessary logs.

File: .github/workflows/run-regression-tests.yml [hunk 3]
```diff
@@ -55,3 +55,13 @@ jobs:
       # Build the plugin.
       - name: 'Test: RunTests'
         run: bash ./src/test/resources/ci/scripts/exec.sh TEST ${{ matrix.targetVSCode }}
+
+      # Archive screenshots
+      - name: Archive screenshots
+        if: always()
```
Comment (aparnamichael) [inline .github/workflows/run-regression-tests.yml:61]: This means screenshot will capture even if tests are success?

File: src/test/MavenTestDevModeActions.ts (hunk 1 above)
Comment (gilbysunil14) [reply src/test/MavenTestDevModeActions.ts:272]: Added the comment.

File: src/test/MavenTestDevModeActions.ts (hunk 2 above)
Comment (gilbysunil14) [reply src/test/MavenTestDevModeActions.ts:281]: Removed.

File: .github/workflows/run-regression-tests.yml (hunk 3 above)
Comment (gilbysunil14) [reply .github/workflows/run-regression-tests.yml:61]: It means that the screenshot will be captured even if the tests are `failed`. In GHA, the following steps after a failure are skipped. `if always()` ensures that the screenshots are archived even if the steps above are failing which means the screenshots will be archived even after a test failure.

**Review by aparnamichael — APPROVED** [review]
Looks good to me!!

File: src/test/resources/ci/scripts/exec.sh [hunk 4]
```diff
@@ -65,8 +65,8 @@ main() {
              if [ $OS = "Darwin" ]; then
                 chown -R runner src/test/resources/maven
               chown -R runner  src/test/resources/gradle
-                npm run test-mac-maven -- -u
```
Comment (aparnamichael) [inline src/test/resources/ci/scripts/exec.sh:68]: Please add a comment here to explaining about this change.

Comment (gilbysunil14) [reply src/test/resources/ci/scripts/exec.sh:68]: added comment

**Review by aparnamichael — APPROVED** [review]

**Review by TrevCraw — APPROVED** [review]
If it is important to get this PR merged ASAP, feel free to open an issue to address the re-design comments. This is good enough for now, but we should consider other options.

Please also open an issue to add test automation documentation to our "developer" documentation file: https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/DEVELOPING.md. As part of the test automation documentation, we should document where to find the screenshots and how to access them.

**Comment by gilbysunil14** [comment]
> If it is important to get this PR merged ASAP, feel free to open an issue to address the re-design comments. This is good enough for now, but we should consider other options.
> 
> Please also open an issue to add test automation documentation to our "developer" documentation file: https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/DEVELOPING.md. As part of the test automation documentation, we should document where to find the screenshots and how to access them.

Opened and issue here: https://github.com/OpenLiberty/liberty-tools-vscode/issues/473

File: .github/workflows/run-regression-tests.yml [hunk 5]
```diff
@@ -55,3 +55,13 @@ jobs:
...
+        uses: actions/upload-artifact@v4.3.4
+        with:
+          name: liberty-run-tests-screenshots-${{ runner.os }}-${{ matrix.targetVSCode }}
+          path: ./screenshots/*.png
+          if-no-files-found: warn
+          retention-days: 7
```
[the remark this answers is not in the document]
Comment (gilbysunil14) [reply .github/workflows/run-regression-tests.yml:67]: Got it! We’ll monitor the situation and adjust the retention period if necessary. I’ll keep you updated on any changes.

File: src/test/MavenTestDevModeActions.ts [hunk 6]
```diff
@@ -273,6 +274,38 @@ it('attach debugger for start with custom parameter event', async () => {
   expect(attachStatus).to.be.true;
 }).timeout(350000);
 
+  /**
+   * The following after hook copies the screenshot from the temporary folder in which it is saved to a known permanent location in the project folder.
+   * The MavenTestDevModeAction is the last test file that will be executed. Hence the after hook placed here
```
[the remark this answers is not in the document]
Comment (gilbysunil14) [reply src/test/MavenTestDevModeActions.ts:279]: This needs to be investigated further. Opened an issue here: https://github.com/OpenLiberty/liberty-tools-vscode/issues/491
